[package]
name = "aoc2025"
version = "0.1.0"
edition = '2024'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.12.2"
itertools = "0.14.0"

[dev-dependencies]
criterion = { version = "0.8.0", features = ["html_reports"] }
